### ISSUE TITLE
trunk build fails with fpc 3.2.0-beta

### ISSUE THREAD

**Issue by szpak** [doublecmd/doublecmd#21]
I don't know if it is a valid place to report the issues (definitely more confortable for most of the users), but doublecmd from trunk (rev. 9300) fails to build with fpc `3.2.0-beta [2020/02/02]` (available in Fedora Rawhide and targetted at Fedora 32) with the following error:
```
(10001) PPU Loading /usr/lib64/lazarus/lcl/units/x86_64-linux/extctrls.ppu
(10011) PPU Source: extctrls.pp not found
(10011) PPU Source: lcl_defines.inc not available
(10011) PPU Source: page.inc not available
(10011) PPU Source: notebook.inc not available
(10011) PPU Source: idletimer.inc not available
(10011) PPU Source: shape.inc not available
(10011) PPU Source: customsplitter.inc not available
(10011) PPU Source: paintbox.inc not available
(10011) PPU Source: customcheckgroup.inc not available
(10011) PPU Source: boundlabel.inc not available
(10011) PPU Source: customlabelededit.inc not available
(10011) PPU Source: custompanel.inc not available
(10011) PPU Source: customflowpanel.inc not available
(10011) PPU Source: radiogroup.inc not available
(10011) PPU Source: bevel.inc not available
(10011) PPU Source: customimage.inc not available
(10011) PPU Source: customtrayicon.inc not available
(10011) PPU Source: controlbar.inc not available
(10028) Recompiling ExtCtrls, checksum changed for /usr/lib64/fpc/3.2.0/units/x86_64-linux/rtl/sysutils.ppu
/builddir/build/BUILD/doublecmd-1.0.0/components/CmdLine/ucmdbox.pas(66,25) Fatal: (10022) Can't find unit ExtCtrls used by uCmdBox
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
Error: (lazarus) Compile package cmdbox 0.0: stopped with exit code 1
Error: (lazbuild) cmdbox 0.0 compilation failed
```
Detected in my weekly [builds](https://github.com/szpak/doublecmd-rpm) of doublecmd for Fedora.  Failing COPR [build](https://download.copr.fedorainfracloud.org/results/vondruch/doublecmd/fedora-rawhide-x86_64/01221666-doublecmd-gtk/build.log.gz).

**Comment by alexx2000** [comment]
I guess it's because Lazarus built with previous Free Pascal version. Lazarus package should be rebuilt.

**Comment by szpak** [comment]
Thanks for your suggestion. I will ask the Lazarus maintainer to do so.

**Comment by szpak** [comment]
Ok, Lazarus [fails](https://kojipkgs.fedoraproject.org//work/tasks/3420/41333420/build.log) to build with new fpc. I try it again once it fixed in Fedora rawhide.

**Comment by alexx2000** [comment]
https://bugs.freepascal.org/view.php?id=36507

**Comment by szpak** [comment]
With the version which seems to be recompiled with the new fpc it [fails](https://download.copr.fedorainfracloud.org/results/vondruch/doublecmd/fedora-rawhide-i386/01228739-doublecmd-gtk/build.log.gz) with:
```
(3104) Compiling ucmdlineparams.pas
(3104) Compiling ./filesources/searchresult/usearchresultfilesource.pas
(3104) Compiling ./filesources/multilist/umultilistfilesource.pas
(3104) Compiling ./filesources/multilist/umultilistlistoperation.pas
/builddir/build/BUILD/doublecmd-1.0.0/src/./filesources/searchresult/usearchresultfilesource.pas(26,29) Error: (5042) No matching implementation for interface method "GetFileList:TFileTreeNode;" found
/builddir/build/BUILD/doublecmd-1.0.0/src/./filesources/searchresult/usearchresultfilesource.pas(26,29) Error: (5042) No matching implementation for interface method "GetFileSource:IFileSource;" found
/builddir/build/BUILD/doublecmd-1.0.0/src/./filesources/searchresult/usearchresultfilesource.pas(40,1) Fatal: (10026) There were 2 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppc386 returned an error exitcode
Error: (lazarus) Compile Project, Mode: Beta, Target: /builddir/build/BUILD/doublecmd-1.0.0/doublecmd: stopped with exit code 1
Error: (lazbuild) failed compiling of project /builddir/build/BUILD/doublecmd-1.0.0/src/doublecmd.lpi
```
Link to the other [logs](https://download.copr.fedorainfracloud.org/results/vondruch/doublecmd/fedora-rawhide-i386/01228739-doublecmd-gtk/).

**Comment by alexx2000** [comment]
Fixed (revision: 9313).

**Comment by szpak** [comment]
Thanks, I will test it once one issue with Travis is solved...

**Comment by szpak** [comment]
The [error](https://download.copr.fedorainfracloud.org/results/vondruch/doublecmd/fedora-rawhide-i386/01237263-doublecmd-gtk/build.log.gz) has changed, but the build still [fails](https://download.copr.fedorainfracloud.org/results/vondruch/doublecmd/fedora-rawhide-i386/01237263-doublecmd-gtk/):
```
(3104) Compiling ./platform/unix/upipeserver.pas
(3104) Compiling ./platform/unix/uxdg.pas
/builddir/build/BUILD/doublecmd-1.0.0/src/./platform/unix/upipeserver.pas(79,46) Error: (4025) Incompatible type for arg no. 2: Got "<procedure variable type of function:Boolean of object;Register>", expected "<procedure variable type of procedure of object;Register>"
upipeserver.pas(164) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppc386 returned an error exitcode
Error: (lazarus) Compile Project, Mode: Beta, Target: /builddir/build/BUILD/doublecmd-1.0.0/doublecmd: stopped with exit code 1
Error: (lazbuild) failed compiling of project /builddir/build/BUILD/doublecmd-1.0.0/src/doublecmd.lpi
```

**Comment by szpak** [comment]
Do you think it is something that could be fixed in DoubleCmd code or it is an incompatibility in fpc?

**Comment by alexx2000** [comment]
Fixed (revision 9321).

**Comment by szpak** [comment]
Confirmed.

![image](https://user-images.githubusercontent.com/148013/74573530-1c284c80-4f81-11ea-9971-0e96bc1ea392.png)


I like my nightly builds with Travis and COPR ;-).
